sudo: required

language: python

services:
  - docker

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  - docker build -t jenkins .
  - docker run -d -p 80:80 jenkins
  - docker ps -a

script:
  - sleep 80
  - curl http://127.0.0.1:80
  - pybot test.robot
