sudo: required

language: python

services:
  - docker

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  - docker build -t jenkins .
  - docker run -d -p 8080:8080 jenkins
  - docker ps -a

script:
  - sleep 30
  - pybot test.robot
