
- project:
    name: workflow
    jobs:
        - 'plone.rest'

- job:
    name: 'plone.rest'
    project-type: workflow
    definitions:
        - script:
            filename: 'plone.rest.pipeline.groovy'
        - scm:
            url: https://github.com/kitconcept/ansible-role-jenkins-plone.git
            branches:
                - '*/master'
