- name: Jenkins
  hosts: 127.0.0.1
  sudo: yes
#  roles:
#    - flyapen.jenkins

  tasks:

    # Set Hostname
    - hostname: name=jenkins.mycompany.com

    # Nginx
    - name: Install Nginx
      apt: name=nginx state=installed
      notify: Restart nginx

    # Install Jenkins
    - apt_key: url=http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key state=present
    - apt_repository: repo='deb http://pkg.jenkins-ci.org/debian-stable binary/' state=present
    - apt: update_cache=yes
    - apt: name=jenkins state=installed
      notify: Restart jenkins

  handlers:

    - name: Restart ssh
      action: service name=ssh state=restarted

    - name: Restart nginx
      action: service name=nginx state=reloaded

    - name: Restart Jenkins
      action: service name=jenkins state=restarted
